SELECT NUM1, NUM2, NUM3, NUM4, NUM5, NUM6, COUNT(*) FROM LOTTO_MAIN GROUP BY NUM1, NUM2, NUM3, NUM4, NUM5, NUM6;

SELECT NUM1, NUM2, NUM3, NUM4, NUM5, NUM6, COUNT(*) FROM LOTTO_MAIN GROUP BY NUM1, NUM2, NUM3, NUM4, NUM5, NUM6 HAVING COUNT(*)>1;

SELECT NUM1 LOTTO_NUM, COUNT(*) CNT FROM LOTTO_MAIN GROUP BY NUM1 ORDER BY 2 DESC;

SELECT LOTTO_NUM, SUM(CNT) AS CNT
FROM (SELECT NUM1 LOTTO_NUM, COUNT(*) CNT
FROM LOTTO_MAIN
GROUP BY NUM1 UNION ALL
SELECT NUM2 LOTTO_NUM, COUNT(*) CNT
FROM LOTTO_MAIN
GROUP BY NUM2 UNION ALL
SELECT NUM3 LOTTO_NUM, COUNT(*) CNT
FROM LOTTO_MAIN
GROUP BY NUM3 UNION ALL
SELECT NUM4 LOTTO_NUM, COUNT(*) CNT
FROM LOTTO_MAIN
GROUP BY NUM4 UNION ALL
SELECT NUM5 LOTTO_NUM, COUNT(*) CNT
FROM LOTTO_MAIN
GROUP BY NUM5 UNION ALL
SELECT NUM6 LOTTO_NUM, COUNT(*) CNT
FROM LOTTO_MAIN
GROUP BY NUM6
) GROUP BY LOTTO_NUM ORDER BY 2 DESC;

SELECT MAX(WIN_MONEY), SEQ_NO FROM LOTTO_DETAIL GROUP BY SEQ_NO HAVING MAX(win_money) > 40000000000;

SELECT A.SEQ_NO, A.LOTTERY_DATE, B.WIN_PERSON_NO, B.WIN_MONEY, A.NUM1, A.NUM2, A.NUM3, A.NUM4, A.NUM5, A.NUM6, A.BOUNUS
FROM LOTTO_MAIN A, LOTTO_DETAIL B WHERE A.SEQ_NO = B.SEQ_NO AND B.RANK_NO = 1 ORDER BY B.WIN_MONEY DESC;
